name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.*' # set this to the .NET Core version to use
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: dotnet build
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release /p:publishdir=${{env.DOTNET_ROOT}}/app

    - name: dotnet test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory "${{env.DOTNET_ROOT}}/app/wwwroot/testresult"
      continue-on-error: true

    - name: upload .net-app
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/app

    - name: bicep build
      uses: Azure/bicep-build-action@v1.0.0
      with:
        bicepFilePath: ./.azure/main.bicep

    - name: upload bicep
      uses: actions/upload-artifact@v3
      with:
        name: .azure
        path: ./azuredeploy.json
        if-no-files-found: 'error'

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: "https://rocmn-${{ github.REPOSITORY_OWNER }}.azurewebsites.net"

    steps:
    - name: download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app
        path: ./.net-app

    - name: download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .azure
        path: ./azure

    - name: az login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: deploy azure resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        parameters: 'webAppName=rocmn-${{ github.REPOSITORY_OWNER }}'
        template: ./azure/azuredeploy.json
        failOnStdErr: fals

    - name: deploy application
      uses: azure/webapps-deploy@v2
      with:
        app-name: rocmn-${{ github.REPOSITORY_OWNER }}
        slot-name: 'Production'
        package: './.net-app'
    
    - name: sleep for 45 seconds
      run: sleep 45s
      shell: bash
      
    - name: warm-up
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 1
        max_attempts: 100
        retry_on: error
        command: wget https://rocmn-${{ github.REPOSITORY_OWNER }}.azurewebsites.net/swagger

    - name: logout
      run: az logout

  notify:
    permissions:
      contents: none
    needs: [build, deploy]
    if: always() #success() || failure()
    runs-on: ubuntu-latest

    steps:
    - name: notify dashboard
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://rocmn-dashboard.azurewebsites.net/api/try'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"team": "${{ github.REPOSITORY_OWNER }}" }'
